# Generated by Django 2.1.5 on 2019-01-10 14:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, through='groups.GroupMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
